module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  testMatch: ["**/*.test.ts"],
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { tsconfig: "<rootDir>/tsconfig.jest.json", diagnostics: false }],
  },
  moduleNameMapper: {
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@services/(.*)$": "<rootDir>/src/services/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@constants/(.*)$": "<rootDir>/src/constants/$1",
    "^@engine/(.*)$": "<rootDir>/src/engine/$1",
    "^@runtime/(.*)$": "<rootDir>/src/runtime/$1",
    "^@extraction/(.*)$": "<rootDir>/src/extraction/$1",
    "^@pacing/(.*)$": "<rootDir>/src/pacing/$1",
    "^@generation/(.*)$": "<rootDir>/src/generation/$1",
    "^@memory/(.*)$": "<rootDir>/src/memory/$1",
    "^@copilot/(.*)$": "<rootDir>/src/copilot/$1",
    "^@talk/(.*)$": "<rootDir>/src/talk/$1",
    "^@wizard/(.*)$": "<rootDir>/src/wizard/$1",
    "^@stagecraft/(.*)$": "<rootDir>/src/stagecraft/$1",
    "^@judge/(.*)$": "<rootDir>/src/judge/$1",
    "\\.css$": "<rootDir>/test/support/styleStub.cjs",
  },
  reporters: ["default", "<rootDir>/scripts/jest-findings-reporter.cjs"],
  clearMocks: true,
  globals: { __SO_DEV__: true },
};
