export const HELP_COPY = {
  toggle: "Help: what each part does",
  heading: "Help",
  intro: "Every part of Story Orchestrator, grouped by what it is for. Show me takes you to its setting; Read more opens its guide page.",
  search: "Search features",
  searchPlaceholder: "memory, images, group…",
  noMatch: "Nothing matches. Try another word.",
  on: "On",
  off: "Off",
  needs: "Needs",
  showMe: "Show me",
  readMore: "Read more",
  where: "Where",
  guideHeading: "Author's guide",
  guideIntro: "Every topic of the story guide. The Studio shows the topics for each tab; all of them are here.",
  close: "Close help",
  whatsNewHeading: "What's new",
  whatsNewIntro: "Added since you last looked:",
  whatsNewDismiss: "Got it",
  gettingStartedHeading: "Getting started",
  gettingStartedHide: "Hide this list",
  optional: "optional",
  done: "Done",
} as const;
