export const HELP_COPY = {
  toggle: "Help: what each part does",
  heading: "Help",
  intro: "Every part of Story Orchestrator, grouped by what it is for. Show me takes you to its setting; Read more opens its guide page.",
  search: "Search features",
  searchPlaceholder: "memory, images, group…",
  noMatch: "Nothing matches. Try another word.",
  on: "On",
  off: "Off",
  needs: "Needs",
  showMe: "Show me",
  readMore: "Read more",
  where: "Where",
  guideHeading: "Author's guide",
  guideIntro: "Every topic of the story guide. The Studio shows the topics for each tab; all of them are here.",
  close: "Close help",
  whatsNewHeading: "What's new",
  whatsNewIntro: "Added since you last looked:",
  whatsNewDismiss: "Got it",
  gettingStartedHeading: "Getting started",
  gettingStartedHide: "Hide this list",
  optional: "optional",
  done: "Done",
} as const;

export const BRIEFING_COPY = {
  beforeYouStart: "Before you start",
  beforeYouStartIntro: "This story cannot play as written until this is fixed:",
  onboarding: "How Story Orchestrator works",
  optOut: "Don't show briefings",
  optOutHelp: "Stops this page opening on its own when a story starts. Story briefing in the drawer still opens it.",
  reopen: "Story briefing",
  reopenHelp: "Read the story's briefing again.",
  close: "Close",
  preview: "Preview",
  noStory: "No story in this chat yet. Choose one under Continue, or start one under Start.",
  openSettings: "Open story settings",
} as const;

export const ONBOARDING_LINES: ReadonlyArray<{ icon: string; text: string }> = [
  { icon: "fa-pen", text: "Write what you do and say. The characters answer, and the story moves on when what it needs has happened." },
  { icon: "fa-route", text: "The route icon in the top bar opens the story drawer: where you are, what happened, and what is still open." },
  { icon: "fa-bars-progress", text: "The strip above where you type shows the scene and the tension. Click it to open the drawer." },
  { icon: "fa-tags", text: "Small icons under replies say what moved the story, what it remembered and which lore it used. Click one to read more." },
  { icon: "fa-brain", text: "The drawer's Memory tab lists what the story remembers. Pin what matters, remove what is wrong." },
  { icon: "fa-terminal", text: "/story recap, /story intro and /story help work from the chat box." },
];

export const GUIDE_COPY = {
  title: "Guide",
  open: "Open the guide",
  back: "Back",
  forward: "Forward",
  search: "Search the guide",
  searchPlaceholder: "memory, images, quests…",
  noMatch: "No page matches. Try another word.",
  pages: "Pages",
  content: "Guide page",
  onGitHub: "Open on GitHub",
  missing: "That page is not available here. Pick one from the list.",
  openInGuide: "Open in the guide",
  close: "Close the guide",
  audience: { player: "Playing", setup: "Setup", author: "Writing stories" },
} as const;
