import { defaultGlobalSettings } from "@runtime/settingsModel";
import { DEFAULT_CHAPTER_SETTINGS } from "@runtime/chapters";
import { isRecord } from "@utils/guards";
import { FEATURE_AREAS, FEATURES, coversSetting, type Feature, type FeatureArea, type FeatureStatus } from "./registry";
import { SETTINGS_AREA_COPY, SETTING_COPY } from "./settingsCopy";

export const FEATURE_TABLE_START = "<!-- features:start (generated by npm run docs:settings; edit src/features/registry.ts) -->";
export const FEATURE_TABLE_END = "<!-- features:end -->";

const REFERENCE_BANNER = "<!-- Generated by npm run docs:settings from src/features/registry.ts and src/features/settingsCopy.ts. Edit those, then run it again. -->";

const ABSENT_DEFAULTS: Record<string, string> = {
  "extraction.fallbackProfileId": "None",
  "extraction.replyEffort": "Medium",
  "extraction.profiles": "Same as memory model",
  "memory.harvestReasoning": "Off",
  "memory.innerBeat": "Off",
  "memory.innerFanOut": "Next speaker only",
};

const STATUS_LABELS: Record<FeatureStatus, string> = { shipped: "", "off-by-default": "Off by default", experimental: "Experimental" };

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

const productDefaults = (): Record<string, unknown> => {
  const defaults = defaultGlobalSettings();
  return { ...defaults, memory: { ...defaults.memory, chapters: DEFAULT_CHAPTER_SETTINGS } };
};

const valueAt = (source: unknown, key: string): unknown => key.split(".").reduce<unknown>((node, part) => (isRecord(node) ? node[part] : undefined), source);

export const formatDefault = (key: string, value: unknown): string => {
  if (key.includes("*")) return "Per entry";
  if (value === undefined) return ABSENT_DEFAULTS[key] ?? "Not set";
  if (value === null || value === "") return "Not set";
  if (typeof value === "boolean") return value ? "On" : "Off";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `\`${value}\``;
  if (Array.isArray(value)) return value.length ? value.map((item) => `\`${String(item)}\``).join(", ") : "None";
  return "Per entry";
};

const GROUP_OWNERS: Record<string, string> = { "judge.uses": "judge", "judge.provider": "judge" };

export const ownerOf = (key: string): Feature | null => {
  const prefix = key.split(".*")[0];
  const grouped = GROUP_OWNERS[prefix];
  if (grouped) return FEATURES.find((feature) => feature.id === grouped) ?? null;
  return FEATURES.find((feature) => feature.settings.some((owned) => coversSetting(owned, prefix) || coversSetting(prefix, owned))) ?? null;
};

export interface SettingRow {
  key: string;
  area: FeatureArea;
  label: string;
  where: string;
  help: string;
  defaultText: string;
}

export const settingRows = (): SettingRow[] => {
  const defaults = productDefaults();
  return Object.entries(SETTING_COPY).map(([key, copy]) => {
    const owner = ownerOf(key);
    return {
      key, area: owner?.area ?? "setup", label: copy.label, where: owner?.where.label ?? "Settings", help: copy.help, defaultText: formatDefault(key, valueAt(defaults, key)),
    };
  });
};

export const renderSettingsReference = (): string => {
  const rows = settingRows();
  const sections = FEATURE_AREAS.flatMap((area) => {
    const inArea = rows.filter((row) => row.area === area);
    if (!inArea.length) return [];
    const copy = SETTINGS_AREA_COPY[area];
    return [
      `## ${copy.label}`,
      "",
      `${copy.oneLine} [More](../${copy.doc})`,
      "",
      "| Setting | Where | What it does | Default | Key |",
      "|---|---|---|---|---|",
      ...inArea.map((row) => `| **${cell(row.label)}** | ${cell(row.where)} | ${cell(row.help)} | ${cell(row.defaultText)} | \`${row.key}\` |`),
      "",
    ];
  });
  return [
    REFERENCE_BANNER,
    "# Settings reference",
    "",
    "Every setting in **Extensions → Story Orchestrator**, by section. Each row says where the control is, what it does, when to change it and what it",
    "costs, and its default. Settings apply to this whole install unless the control says \"this chat\". Rarely changed settings sit under their",
    "section's **Advanced** fold.",
    "",
    ...sections,
    "---",
    "",
    "[Setup](README.md)",
    "",
  ].join("\n");
};

export const readmeFeatures = (): Feature[] => FEATURES.filter((feature) => !feature.id.startsWith("judge-use-"));

export const renderFeatureTable = (): string => [
  "| Area | Feature | In one line | Status |",
  "|---|---|---|---|",
  ...FEATURE_AREAS.flatMap((area) => readmeFeatures().filter((feature) => feature.area === area)
    .map((feature) => `| ${SETTINGS_AREA_COPY[area].label} | ${cell(feature.name)} | ${cell(feature.oneLine)} | ${STATUS_LABELS[feature.status]} |`)),
].join("\n");

export const spliceFeatureTable = (readme: string): string => {
  const text = readme.replace(/\r\n/g, "\n");
  const start = text.indexOf(FEATURE_TABLE_START);
  const end = text.indexOf(FEATURE_TABLE_END);
  if (start < 0 || end < start) throw new Error(`README.md has no ${FEATURE_TABLE_START} … ${FEATURE_TABLE_END} block`);
  return `${text.slice(0, start)}${FEATURE_TABLE_START}\n${renderFeatureTable()}\n${text.slice(end)}`;
};
