import { writeFile } from 'node:fs/promises';
import { connectToST } from '../../../scripts/debug/lib/connection.mts';
import { openStoryDrawer, switchStudioTab, getGateReplayState, getGateReplayHistory } from '../../../scripts/debug/so-ui.mts';

const out = process.argv[2];
const { page } = await connectToST();
const result: Record<string, unknown> = {};
result.history = await getGateReplayHistory(page).then((h: any) => ({ storyId: h?.storyId, boundaries: h?.engineHistory?.log?.length }));
await page.evaluate(() => (globalThis as any).storyOrchestratorRuntime.setUiSettings({ authorView: true }));
await openStoryDrawer(page);
const tabs = page.locator('#drawer-manager [role="tablist"] button', { hasText: 'Overview' });
if (await tabs.count()) await tabs.first().click();
await page.locator('#so-edit-story').click();
await page.locator('#so-studio-modal').waitFor({ state: 'visible', timeout: 15000 });
await page.waitForTimeout(800);
await switchStudioTab(page, 'Transitions');
result.transitionButtons = await page.locator('#so-studio-modal ul[aria-label="Transitions"] button').allTextContents();
result.t1Before = await getGateReplayState(page, { transition: 1 });
const op = page.locator('#so-studio-modal select[aria-label="Gate operator"]').first();
result.t1OpBefore = await op.inputValue();
await op.selectOption('!=');
await page.waitForTimeout(500);
result.t1OpAfter = await op.inputValue();
result.t1After = await getGateReplayState(page, { transition: 1 });
result.t0Unchanged = await getGateReplayState(page, { transition: 0 });
result.draftGates = await page.evaluate(() => (globalThis as any).storyOrchestratorStudioDraft.getState().draft?.transitions?.slice(0, 2).map((t: any) => ({ from: t.from, to: t.to, gate: t.gate })));
await page.screenshot({ path: out.replace(/\.json$/, '.png') });
await writeFile(out, JSON.stringify(result, null, 2));
console.log(JSON.stringify(result, null, 2));
process.exit(0);
