import { writeFile } from 'node:fs/promises';
import { connectToST } from '../../../scripts/debug/lib/connection.mts';
import { getGateReplayState } from '../../../scripts/debug/so-ui.mts';
const out = process.argv[2];
const { page } = await connectToST();
const r: Record<string, unknown> = {};
await page.locator('#so-studio-modal ul[aria-label="Transitions"] button').nth(1).click();
await page.locator('#so-studio-modal select[aria-label="Gate quality"]').first().selectOption('approached_board');
await page.waitForTimeout(300);
await page.locator('#so-studio-modal select[aria-label="Gate value"]').first().selectOption('true');
await page.waitForTimeout(500);
r.t1Edited = await getGateReplayState(page, { transition: 1 });
r.t0Unchanged = await getGateReplayState(page, { transition: 0 });
r.draftGates = await page.evaluate(() => (globalThis as any).storyOrchestratorStudioDraft.getState().draft?.transitions?.slice(0, 2).map((t: any) => ({ from: t.from, to: t.to, gate: t.gate })));
await page.locator('#so-studio-modal ul[aria-label="Transitions"] button').nth(1).click();
await page.waitForTimeout(300);
await page.screenshot({ path: out.replace(/\.json$/, '.png') });
await writeFile(out, JSON.stringify(r, null, 2));
console.log(JSON.stringify(r, null, 2));
process.exit(0);
