import { writeFile } from 'node:fs/promises';
import { connectToST } from '../../../../../../scripts/debug/lib/connection.mts';
import { openStoryDrawer, switchStudioTab, getGateReplayState, getGateReplayHistory } from '../../../../../../scripts/debug/so-ui.mts';

const out = process.argv[2];
const { page } = await connectToST();
const r: Record<string, unknown> = {};
const history = await getGateReplayHistory(page);
r.history = { storyId: history?.storyId, boundaries: history?.engineHistory?.log?.length, fires: history?.engineHistory?.log?.filter((e: any) => e.fired).length };
r.chat = await page.evaluate(() => ({ chatId: SillyTavern.getContext().chatId, groupId: SillyTavern.getContext().groupId, len: SillyTavern.getContext().chat.length }));
await page.evaluate(() => (globalThis as any).storyOrchestratorRuntime.setUiSettings({ authorView: true }));
await openStoryDrawer(page);
const overview = page.locator('#drawer-manager [role="tablist"] button', { hasText: 'Overview' });
if (await overview.count()) await overview.first().click();
await page.locator('#so-edit-story').click();
await page.locator('#so-studio-modal').waitFor({ state: 'visible', timeout: 15000 });
await page.waitForTimeout(800);
await switchStudioTab(page, 'Transitions');
r.transitionButtons = await page.locator('#so-studio-modal ul[aria-label="Transitions"] button').allTextContents();
r.t1 = await getGateReplayState(page, { transition: 1 });
await page.screenshot({ path: out.replace(/\.json$/, '-t1.png') });
r.t0 = await getGateReplayState(page, { transition: 0 });
await page.screenshot({ path: out.replace(/\.json$/, '-t0.png') });
const check = (s: any) => (s?.rows ?? []).map((row: any) => ({ boundary: row.boundary, jumpW: row.layout?.jump?.width, jumpH: row.layout?.jump?.height, verdictInList: row.layout?.verdictInList, ok: row.layout?.jump?.width > 80 && row.layout?.jump?.height < 40 && row.layout?.verdictInList === true }));
r.checks = { t1: check(r.t1), t0: check(r.t0) };
const all = [...(r.checks as any).t1, ...(r.checks as any).t0];
r.verdict = { rows: all.length, pass: all.length > 0 && all.every((x: any) => x.ok) };
await page.keyboard.press('Escape');
await page.evaluate(() => (globalThis as any).storyOrchestratorRuntime.setUiSettings({ authorView: false }));
await writeFile(out, JSON.stringify(r, null, 2));
console.log(JSON.stringify(r, null, 2));
process.exit(0);
