// v2.4 plan 01 (X10): the P0′ transcript → scenario converter that plan 09 row R1 replays.
// Input is the ST chat file the playthrough left (`data/<user>/chats|group chats/<id>.jsonl`): its
// header carries the pinned story, its user rows are the player's lines. The output re-sends each
// line as a real generation and logs one per-turn record, so a replay at a later build is diffed
// turn by turn against the original. The record is a log, not a gate: nothing in it asserts.
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateFixture } from './lib/scenarioSchema.mts';

const USAGE = `Usage: node scripts/debug/p0-replay.mts convert <chat.jsonl> --out <scenario.json> [--timeout-ms 300000] [--quiet-ms 5000]

Converts a recorded chat (the P0′ playthrough) into a so-scenario fixture that imports the story the
chat pinned and re-sends every player line through a real generation, logging after each turn:
boundary, active checkpoint, path, blackboard values, and the extraction reads since the last turn
(accepted and rejected counts, rejected reasons). Run it with:
  node scripts/debug/so-scenario.mts run <scenario.json> --sandbox --group <id>`;

type ChatRow = { is_user?: boolean; is_system?: boolean; name?: string; mes?: string; send_date?: string; extra?: { type?: string } };
type ChatHeader = { chat_metadata?: { story_orchestrator?: { selectedStoryId?: string | null; stories?: Record<string, { pinnedStory?: unknown; contentHashAtLoad?: string }> } } };

export type ReplaySource = { header: ChatHeader; rows: ChatRow[] };

export function parseChatFile(text: string): ReplaySource {
  const lines = text.split(/\r?\n/).filter((line) => line.trim());
  if (!lines.length) throw new Error('empty chat file');
  const [first, ...rest] = lines.map((line, index) => {
    try { return JSON.parse(line); } catch { throw new Error(`line ${index + 1} is not JSON`); }
  });
  if (!first || typeof first !== 'object' || !('chat_metadata' in first)) throw new Error('line 1 is not a chat header (no chat_metadata)');
  return { header: first as ChatHeader, rows: rest as ChatRow[] };
}

export const playerLines = (rows: ChatRow[]) => rows
  .filter((row) => row.is_user === true && !row.extra?.type && String(row.mes ?? '').trim())
  .map((row) => ({ text: String(row.mes), hidden: row.is_system === true }));

export function pinnedStory(header: ChatHeader) {
  const blob = header.chat_metadata?.story_orchestrator;
  const id = blob?.selectedStoryId ?? null;
  const entry = id ? blob?.stories?.[id] : undefined;
  if (!id || !entry?.pinnedStory) throw new Error(`the chat pins no story (selectedStoryId ${JSON.stringify(id)}): a replay needs the story the playthrough ran`);
  return { id, hash: entry.contentHashAtLoad ?? null, story: entry.pinnedStory };
}

export const turnRecordEval = (turn: number) => [
  'const rt = globalThis.storyOrchestratorRuntime;',
  'const state = rt.getEngineState();',
  'const audits = rt.getExtractionAudits();',
  'const from = globalThis.__soReplayAuditCursor ?? 0;',
  'globalThis.__soReplayAuditCursor = audits.length;',
  'const reads = audits.slice(from);',
  `return { turn: ${turn}, boundary: state?.boundary ?? null, active: state?.activeCheckpointId ?? null, path: state?.visitedPath ?? [], values: state?.blackboard?.values ?? {}, reads: reads.length, accepted: reads.flatMap((audit) => audit.acceptedDeltas.map((entry) => entry.delta.q + '=' + JSON.stringify(entry.delta.v))), rejected: reads.flatMap((audit) => audit.rejected.map((entry) => entry.reason)) };`,
].join(' ');

export type ConvertOptions = { source: string; sourceSha256: string; timeoutMs?: number; quietMs?: number };

export function transcriptToScenario({ header, rows }: ReplaySource, options: ConvertOptions) {
  const pinned = pinnedStory(header);
  const lines = playerLines(rows);
  if (!lines.length) throw new Error('the chat has no player lines to replay');
  const timeoutMs = options.timeoutMs ?? 300000;
  const quietMs = options.quietMs ?? 5000;
  const hidden = lines.filter((line) => line.hidden).length;
  const steps: unknown[] = [
    { import_story: pinned.story },
    { eval: 'globalThis.__soReplayAuditCursor = globalThis.storyOrchestratorRuntime.getExtractionAudits().length; return { cursor: globalThis.__soReplayAuditCursor };' },
    { eval: turnRecordEval(0), log: true },
  ];
  lines.forEach((line, index) => {
    steps.push(
      { send_generate: { text: line.text, timeoutMs } },
      { wait: { schedulerIdle: true, quietMs, timeoutMs } },
      { eval: turnRecordEval(index + 1), log: true },
    );
  });
  return {
    _note: `P0′ matched replay (v2.4 plan 09 R1), generated by p0-replay.mts from ${options.source} (sha256 ${options.sourceSha256}): story ${pinned.id} (${pinned.hash ?? 'no hash'}), ${lines.length} player line(s)${hidden ? `, ${hidden} of them hidden in the original` : ''}. Each line is its final text: an edit made during play is replayed as edited, never as first typed. Recorded, not scored.`,
    steps,
  };
}

async function main(args: string[]) {
  if (args[0] !== 'convert' || !args[1] || args.includes('--help') || args.includes('-h')) {
    console.log(USAGE);
    process.exitCode = args[0] === 'convert' || !args.length ? 1 : 0;
    return;
  }
  const flag = (name: string) => { const at = args.indexOf(name); return at >= 0 ? args[at + 1] : undefined; };
  const out = flag('--out');
  if (!out) throw new Error('--out <scenario.json> is required');
  const path = resolve(args[1]);
  const text = await readFile(path, 'utf-8');
  const scenario = transcriptToScenario(parseChatFile(text), {
    source: basename(path),
    sourceSha256: createHash('sha256').update(text).digest('hex'),
    timeoutMs: flag('--timeout-ms') ? Number(flag('--timeout-ms')) : undefined,
    quietMs: flag('--quiet-ms') ? Number(flag('--quiet-ms')) : undefined,
  });
  const problems = validateFixture(scenario);
  if (problems.length) throw new Error(`the generated scenario does not validate: ${problems.join('; ')}`);
  await writeFile(resolve(out), `${JSON.stringify(scenario, null, 2)}\n`);
  console.log(JSON.stringify({ ok: true, out: resolve(out), turns: (scenario.steps.length - 3) / 3 }, null, 2));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
}
