#!/usr/bin/env node
// v2.6 plan 13 R3 + R5: one call per test asset (docs/plans/v2.6/13-decisions.md) and the final LLM suite with its
// lane-time total (docs/plans/v2.6/13-final-suite.md). Rules live in scripts/lib/suiteDecisions.mjs; the calls a
// rule cannot make, the measured journey durations and the placeholder rows live in test/findings/suite-decisions.json.
//
//   node scripts/suite/decisions.mjs [--replay test/findings/defect-replay-report.json] [--mutation docs/plans/v2.6/13-mutation-baseline.json]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collect } from './inventory.mjs';
import { decideAsset, journeyMinutes, suiteBudget } from '../lib/suiteDecisions.mjs';
import { mdCell } from '../lib/suiteInventory.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const INPUT = join(ROOT, 'test', 'findings', 'suite-decisions.json');
const arg = (name, fallback) => {
  const at = process.argv.indexOf(name);
  return at >= 0 ? process.argv[at + 1] : fallback;
};

function main() {
  const config = JSON.parse(readFileSync(INPUT, 'utf-8'));
  const replayPath = arg('--replay', join(ROOT, 'test', 'findings', 'defect-replay-report.json'));
  const data = collect({ replayPath: existsSync(replayPath) ? replayPath : null });
  const mutationPath = arg('--mutation', join(ROOT, 'docs', 'plans', 'v2.6', '13-mutation-baseline.json'));
  const mutation = existsSync(mutationPath) ? JSON.parse(readFileSync(mutationPath, 'utf-8')) : null;

  const rows = [
    ...data.jestRows.map((row) => ({ tier: 'jest', asset: row.path, ...decideAsset('jest', row, config) })),
    ...data.stories.map((row) => ({ tier: 'storybook', asset: row.path, ...decideAsset('storybook', row, config) })),
    ...data.harness.map((row) => ({ tier: 'harness', asset: row.path, ...decideAsset('harness', row, config) })),
    ...data.scenarios.filter((row) => row.shape).map((row) => ({ tier: row.shape.needsLlm ? 'LLM scenario' : 'no-LLM scenario', asset: row.path, est: row.est, ...decideAsset('scenario', row, config) })),
    ...data.journeys.map((row) => ({ tier: 'journey check', asset: row.id, journey: row.journey, llm: row.shape.needsLlm, ...decideAsset('journey', row, config) })),
    ...data.liveSuite.map((row) => ({ tier: 'live suite', asset: row.name, ...decideAsset('live', row, config) })),
    ...config.retired.map((row) => ({ tier: 'retired', asset: row.path, decision: row.decision, reason: row.reason })),
  ];

  const tally = new Map();
  for (const row of rows) {
    const key = `${row.tier}\u0001${row.decision}`;
    tally.set(key, (tally.get(key) ?? 0) + 1);
  }
  const D = [];
  D.push('# v2.6 plan 13 R3 — per-asset decisions (generated)');
  D.push('');
  D.push('Generated by `node scripts/suite/decisions.mjs` from the inventory (`scripts/suite/inventory.mjs`), the rules in `scripts/lib/suiteDecisions.mjs` and the hand calls in `test/findings/suite-decisions.json`. Re-run it; do not edit by hand.');
  D.push('');
  D.push('Decisions: **keep** (guards something named, or is the cheap deterministic tier), **merge** (fold into one parameterised asset; both halves stay until the merged one exists), **demote** (a measurement, not regression: out of the final suite, per budget rule 4), **retire** (deleted from `test/`, reachable in git history), **fix** (vacuous; kept out of any coverage claim until fixed).');
  D.push('');
  D.push('Rules applied:');
  D.push('- Nothing that guards a named invariant or defect is retired; a retire needs the defect replay to stay 25/25 (it does: `npm run test:replay`).');
  D.push('- jest and Storybook are kept whole: 342 jest files cost 199 s summed, and retiring one file needs its own mutation run to prove nothing is lost, which the sampled baseline cannot give per file. A jest file that names no guard is kept and flagged `unnamed` — budget rule 1 applies on its next touch.');
  D.push('- An LLM scenario that is a spike leg or a calibration arm is demoted to measurement; the rest are kept or named as merge candidates.');
  D.push('- A vacuous needle whose fix would redefine a reported number waits for its owner\'s decision (X15), and says so.');
  D.push('');
  D.push('## Summary');
  D.push('');
  D.push('| Tier | Decision | Assets |');
  D.push('|---|---|---|');
  for (const [key, count] of [...tally].sort()) {
    const [tier, decision] = key.split('\u0001');
    D.push(`| ${tier} | ${decision} | ${count} |`);
  }
  D.push('');
  if (mutation) {
    D.push(`Mutation baseline (R2, \`docs/plans/v2.6/13-mutation-baseline.json\`): ${(mutation.total.score * 100).toFixed(1)}% killed of ${mutation.total.scored} scored mutants (sample ${mutation.sample} of ${mutation.population}, seed ${mutation.seed}). The R3 gate "not lower after pruning" holds by construction for this wave: no jest file was retired, so the same sample runs against the same tests.`);
    D.push('');
  }
  D.push('## Every asset');
  D.push('');
  D.push('| Tier | Asset | Decision | Reason |');
  D.push('|---|---|---|---|');
  for (const row of rows) D.push(`| ${row.tier} | \`${row.asset}\` | ${row.decision} | ${mdCell(row.reason)} |`);
  D.push('');
  writeFileSync(join(ROOT, 'docs', 'plans', 'v2.6', '13-decisions.md'), D.join('\n'), 'utf-8');

  const journeys = new Map();
  for (const row of data.journeys) {
    const entry = journeys.get(row.journey) ?? { id: row.journey, file: row.path.split('/').pop(), checks: 0, llm: 0, human: 0, estSeconds: 0 };
    entry.checks += 1;
    entry.llm += row.shape.needsLlm ? 1 : 0;
    entry.human += row.mode === 'human' ? 1 : 0;
    entry.estSeconds += row.est;
    journeys.set(row.journey, entry);
  }
  const journeyRows = [...journeys.values()].sort((a, b) => Number(a.id.slice(1)) - Number(b.id.slice(1)) || a.id.localeCompare(b.id)).map((entry) => ({ ...entry, ...journeyMinutes(entry, config) }));
  const llmScenarios = rows.filter((row) => row.tier === 'LLM scenario' && (row.decision === 'keep' || row.decision.startsWith('merge')));
  const noLlm = rows.filter((row) => row.tier === 'no-LLM scenario' && row.decision === 'keep');
  const sections = [
    { name: 'no-LLM scenarios (phase F step 1, any lane)', minutes: Math.round(noLlm.reduce((sum, row) => sum + row.est, 0) / 60), llm: false, rows: [{ id: `${noLlm.length} fixtures`, what: 'every kept no-LLM scenario (13-decisions.md)', minutes: Math.round(noLlm.reduce((sum, row) => sum + row.est, 0) / 60) }] },
    { name: 'journeys', llm: true, rows: journeyRows.map((entry) => ({ id: entry.id, what: `\`${entry.file}\`: ${entry.checks} checks (${entry.llm} need a model, ${entry.human} human, scored in plan 10's sessions)`, minutes: entry.minutes, note: entry.source })) },
    { name: 'live scenarios kept by R3', llm: true, rows: llmScenarios.map((row) => ({ id: row.asset.split('/').pop().replace(/\.json$/, ''), what: row.decision === 'keep' ? 'kept' : row.decision, minutes: Math.round((row.est + config.overheadMinutes * 60) / 60) })) },
    ...config.placeholders.map((section) => ({ name: section.section, llm: true, rows: section.rows })),
  ];
  const budget = suiteBudget(sections, config, rows.filter((row) => row.decision === 'demote'));
  const S = [];
  S.push('# v2.6 plan 13 R5 — the final LLM suite (generated)');
  S.push('');
  S.push('Generated by `node scripts/suite/decisions.mjs`. Plan 10 phase F runs this list, in this order, from `adolion-fresh`, ×2. Rows from plans not yet built are **placeholders** (marked), sized from their plan text; each owning plan replaces its placeholder with its real row list and re-runs this script.');
  S.push('');
  S.push(`Lane time per row: a measured median where archived records hold one (journeys), else the step estimate (45 s per real generation, 20 s per unmocked model pass, 2 s per step) plus ${config.overheadMinutes} min setup/cleanup; placeholders carry their plan's own sizing. Lanes: ${config.lanes} LLM-heavy lanes (llama-server \`LLM_PARALLEL\` 2), a night = ${config.nightHours} h.`);
  S.push('');
  S.push('## Budget');
  S.push('');
  S.push('| | Sized (lane-h) | Phase F cap (lane-h) |');
  S.push('|---|---|---|');
  for (const section of budget.sections) S.push(`| ${section.name}${section.llm ? '' : ' (no model)'} | ${(section.minutes / 60).toFixed(1)} | ${(section.capped / 60).toFixed(1)} |`);
  S.push(`| **one pass (LLM rows)** | **${budget.llmHours.toFixed(1)}** | **${budget.cappedHours.toFixed(1)}** |`);
  S.push(`| **x2** | **${(budget.llmHours * 2).toFixed(1)}** | **${(budget.cappedHours * 2).toFixed(1)}** |`);
  S.push(`| capacity: 2 nights x ${config.nightHours} h x ${config.lanes} lanes | ${budget.capacityHours.toFixed(1)} | ${budget.capacityHours.toFixed(1)} |`);
  S.push('');
  S.push(`The cut already applied by R3: ${budget.demotedCount} LLM scenarios demoted (spike legs, calibration arms, and LLM scenarios that name no guard; ${(budget.demotedMinutes / 60).toFixed(1)} lane-hours per pass by the step estimate) and 1 duplicate retired. ${config.cutNote}`);
  S.push('');
  const builtHours = budget.sections.filter((section) => section.llm && ['journeys', 'live scenarios kept by R3'].includes(section.name)).reduce((sum, section) => sum + section.capped, 0) / 60;
  S.push(budget.fitsCapped
    ? `**Fits at the caps**: x2 needs ${(budget.cappedHours * 2).toFixed(1)} of ${budget.capacityHours.toFixed(1)} lane-hours.`
    : `**Does not fit, even at the caps**: x2 needs ${(budget.cappedHours * 2).toFixed(1)} of ${budget.capacityHours.toFixed(1)} lane-hours, ${budget.gapHours.toFixed(1)} over (at the plans' own sizing: ${(budget.llmHours * 2).toFixed(1)}). The rows already built (journeys, live scenarios) take ${(builtHours * 2).toFixed(1)} lane-hours x2; the rest is placeholder rows for plans not yet built. Closing the gap is a plan 10 / user call, not a silent cut: a third night, integration (09) x2 on its own night, or the measurement-adjacent rows (03, 05 R3) x1 in phase F.`);
  S.push('');
  for (const section of sections) {
    S.push(`## ${section.name}`);
    S.push('');
    S.push('| Row | What | Minutes | Phase F cap | Note |');
    S.push('|---|---|---|---|---|');
    for (const row of section.rows) S.push(`| ${row.id} | ${mdCell(row.what)} | ${row.minutes} | ${typeof row.capMinutes === 'number' ? row.capMinutes : row.minutes} | ${mdCell([row.note, row.capReason].filter(Boolean).join('; '))} |`);
    S.push('');
  }
  S.push('## Demoted (not in the suite; files kept)');
  S.push('');
  for (const row of rows.filter((entry) => entry.decision === 'demote')) S.push(`- \`${row.asset}\` (~${Math.round(row.est / 60)} min): ${row.reason}`);
  S.push('');
  writeFileSync(join(ROOT, 'docs', 'plans', 'v2.6', '13-final-suite.md'), S.join('\n'), 'utf-8');
  console.log(`decisions: ${rows.length} assets; final suite one pass ${budget.llmHours.toFixed(1)} lane-h sized, ${budget.cappedHours.toFixed(1)} capped; x2 capped ${(budget.cappedHours * 2).toFixed(1)} of ${budget.capacityHours} (${budget.fitsCapped ? 'fits' : `DOES NOT FIT by ${budget.gapHours.toFixed(1)}`})`);
  return 0;
}

const invoked = process.argv[1] ? process.argv[1].replace(/\\/g, '/').toLowerCase() : '';
if (fileURLToPath(import.meta.url).replace(/\\/g, '/').toLowerCase() === invoked) process.exitCode = main();
