import { test } from 'node:test';
import assert from 'node:assert/strict';
import { acceptBaseline, buildInventory, buildManifest, castResetPlan, checkInventory, IMAGE_EXTENSION, imageExtensionProblems, lastGoodSeed, seedDrift, expectedStartDisabled, diffInventories, installerProblems, isLfsPointer, laneProfiles, mirrorName, parseGroupScript, spriteFolders, stripPlan, type InventoryInput } from './adolionFresh.mts';


const GROUP_SCRIPT = `// Generated by scripts/write_group_script.py. Do not edit; rerun the script.
const gc = await import('/scripts/group-chats.js');
const GROUPS = [
 { "name": "Adolion - House Nightriver", "story": "adolion-academy", "members": ["Adolion Narrator.png", "Natalia.png"] },
 { "name": "Adolion - Eshalanore", "story": "adolion-esha", "members": ["Adolion Narrator.png", "Belle.png"] }
];
const out = [];
return out;`;

const book = (count: number) => ({ entries: Object.fromEntries(Array.from({ length: count }, (_, uid) => [String(uid), { uid, key: [`k${uid}`], content: `c${uid}`, disable: uid > 0 }])) });

const FIXED = ['Adolion World', 'Adolion Chronicle', 'Adolion - Aegis City Noble Life', 'Adolion - The Third Kingdom', 'Adolion - Tiunhime Village', 'Adolion - Eshalanore', 'Adolion - Mountains of Shadow'];

const manifest = buildManifest({
  commit: 'abc123',
  stories: [
    { id: 'adolion-academy', version: 21, title: 'House Nightriver', checkpoints: [{}, {}], requirements: { lorebooks: ['Adolion World', 'Adolion Academy Checkpoints'], members: ['Adolion Narrator', 'Natalia'] } },
    { id: 'adolion-esha', version: 6, title: 'Adolion: Eshalanore', checkpoints: [{ effects: { cast_changes: { disable: ['Belle', 'Natalia'], enable: ['Natalia'] } } }], requirements: { lorebooks: ['Adolion World', 'Adolion - Eshalanore'], members: ['Adolion Narrator', 'Belle'] } },
  ],
  cards: ['Adolion Narrator', 'Natalia', 'Belle'].map((name) => ({ avatar: `${name}.png`, data: { data: { name } } })),
  books: [
    ...FIXED.map((name) => ({ name, data: book(2) })),
    { name: 'Adolion Academy Checkpoints', data: book(3) },
    { name: 'Adolion World.report', data: book(1) },
    { name: 'Adolion Adventurer Checkpoints.v1', data: book(1) },
  ],
  groupScript: GROUP_SCRIPT,
  sprites: spriteFolders([
    { name: 'Natalia', sets: [{ id: 'default', labels: ['neutral', 'happy'], neutral: true }, { id: 'ball', labels: ['neutral'], neutral: true }, { id: 'draft', labels: ['happy'], neutral: false }] },
    { name: 'Belle', folder: 'Belle Nabba', sets: [{ id: 'default', labels: ['neutral'], neutral: true }] },
    { name: 'Nobody', sets: [{ id: 'default', labels: ['neutral'], neutral: true }] },
    { name: 'Adolion Narrator', sets: [{ id: 'night', labels: ['neutral'], neutral: true }] },
  ], ['Adolion Narrator', 'Natalia', 'Belle']),
});

const cleanInput = (): InventoryInput => ({
  commit: 'abc123',
  books: [...FIXED.map((name) => ({ name, data: book(2) })), { name: 'Adolion Academy Checkpoints', data: book(3) }, { name: 'Xentar Checkpoints', data: book(4) }],
  characters: ['Adolion Narrator.png', 'Natalia.png', 'Belle.png', 'Seraphina.png'],
  groups: [
    { id: '17', name: 'Adolion - House Nightriver', members: ['Natalia.png', 'Adolion Narrator.png'], disabled_members: [] },
    { id: '18', name: 'Adolion - Eshalanore', members: ['Belle.png', 'Adolion Narrator.png'], disabled_members: ['Belle.png'] },
    { id: '5', name: 'AdolionGroup', members: ['Belle.png'] },
  ],
  settings: {
    extension_settings: { 'story-orchestrator': {
      groupStories: { 17: 'adolion-academy', 18: 'adolion-esha' },
      v2Stories: [
        { id: 'adolion-academy', version: 21, hash: 'h1', title: 'House Nightriver', raw: { checkpoints: [{}, {}] } },
        { id: 'adolion-esha', version: 6, hash: 'h2', title: 'Adolion: Eshalanore', raw: { checkpoints: [{}] } },
        { id: 'so-j9-wizard', version: 1, hash: 'h3', title: 'Wizard', raw: {} },
      ],
      settings: { extraction: { enabled: true, cadence: 1, stabilityLag: 0, profileId: 'p' }, image: { enabled: false, comfyUrl: '' }, sprites: { enabled: false, explicit: true } },
    } },
    world_info_settings: { world_info: { globalSelect: [] as string[] } },
  },
  ledger: { lorebooks: manifest.books.map((entry) => entry.name), characters: manifest.cards.map((card) => card.avatar) },
  sprites: [{ folder: 'Natalia', labels: ['happy', 'neutral', 'extra'] }, { folder: 'Natalia/ball', labels: ['neutral'] }, { folder: 'Belle Nabba', labels: ['neutral'] }],
  runtime: {
    'adolion-academy': { ready: true, storyId: 'adolion-academy', missingLorebooks: [], missingMembers: [], missingPersonas: [] },
    'adolion-esha': { ready: true, storyId: 'adolion-esha', missingLorebooks: [], missingMembers: [], missingPersonas: [] },
  },
});

test('the manifest follows the installer: working copies and reports are not books, required books are the union', () => {
  assert.deepEqual(manifest.books.map((entry) => entry.name).sort(), [...FIXED, 'Adolion Academy Checkpoints'].sort());
  assert.deepEqual(manifest.requiredBooks, ['Adolion - Eshalanore', 'Adolion Academy Checkpoints', 'Adolion World']);
  assert.deepEqual(manifest.groups.map((group) => group.story), ['adolion-academy', 'adolion-esha']);
  assert.throws(() => parseGroupScript('const x = 1;'), /no `const GROUPS/);
});

test('sprite packs follow the installer: a pack needs a default neutral, a set without a neutral is skipped, a pack without a card is not ours', () => {
  assert.deepEqual(manifest.sprites, [
    { folder: 'Belle Nabba', labels: ['neutral'] },
    { folder: 'Natalia', labels: ['happy', 'neutral'] },
    { folder: 'Natalia/ball', labels: ['neutral'] },
  ]);
  assert.equal(isLfsPointer('version https://git-lfs.github.com/spec/v1\noid sha256:'), true);
  assert.equal(isLfsPointer('\u0089PNG'), false);
});

test('a sprite missing from the lane, or no sprite packs in the build, fails the check', () => {
  const input = cleanInput();
  input.sprites = [{ folder: 'Natalia', labels: ['neutral'] }, { folder: 'Belle Nabba', labels: ['neutral'] }];
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.includes('sprites Natalia: 1 of 2 missing (happy)'));
  assert.ok(problems.includes('sprites Natalia/ball: 1 of 1 missing (neutral)'));
  const bare = { ...manifest, sprites: [] };
  assert.ok(checkInventory(bare, buildInventory(bare, cleanInput())).includes('the pinned build has no sprite packs (the sprite checkout is missing or empty)'));
});

test('a clean seed passes the check, and a stranger\'s book, card or story is not counted as ours', () => {
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, cleanInput())), []);
});

test('a planted missing book fails the check and names every story it leaves unready', () => {
  const input = cleanInput();
  input.books = input.books.filter((entry) => entry.name !== 'Adolion - Eshalanore');
  input.runtime!['adolion-esha'] = { ready: false, storyId: 'adolion-esha', missingLorebooks: ['Adolion - Eshalanore'], missingMembers: [], missingPersonas: [] };
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.includes('book missing: Adolion - Eshalanore'), problems.join('\n'));
  assert.ok(problems.some((line) => line.startsWith('story adolion-esha not ready (install): lorebooks [Adolion - Eshalanore]')));
  assert.ok(problems.some((line) => line.startsWith('story adolion-esha not ready (runtime')));
  assert.ok(!problems.some((line) => line.startsWith('story adolion-academy')));
});

test('a listed story book needs no global selection, and any book selected for every chat fails the check', () => {
  const input = cleanInput();
  assert.ok(!checkInventory(manifest, buildInventory(manifest, input)).some((line) => line.includes('not ready (install)')));
  input.settings.world_info_settings.world_info.globalSelect = ['Adolion World', 'Xentar Checkpoints'];
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.includes('books selected for every chat (each story loads its own books in its own chats): Adolion World, Xentar Checkpoints'), problems.join('\n'));
  assert.ok(!problems.some((line) => line.includes('not ready (install)')));
});

test('an installer SKIP, a lost group binding, a stale library version and a missing member each fail', () => {
  const input = cleanInput();
  input.ledger = { lorebooks: input.ledger!.lorebooks!, characters: ['Natalia.png'] };
  input.settings.extension_settings['story-orchestrator'].groupStories = { 17: 'adolion-academy' };
  input.settings.extension_settings['story-orchestrator'].v2Stories[0].version = 20;
  input.characters = input.characters.filter((avatar) => avatar !== 'Natalia.png');
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.some((line) => line.startsWith('installer ledger cards differ')));
  assert.ok(problems.includes('group Adolion - Eshalanore: bound to nothing, want adolion-esha'));
  assert.ok(problems.some((line) => line.startsWith('story adolion-academy: library v20')));
  assert.ok(problems.includes('cards missing: Natalia.png'));
  assert.ok(problems.some((line) => line.startsWith('story adolion-academy not ready (install): lorebooks [] members [Natalia]')));
  assert.deepEqual(installerProblems('lorebook Adolion World (264 entries)\nSKIP card \'Belle\': already installed\nFAIL card \'X\': {}'), ["SKIP card 'Belle': already installed", "FAIL card 'X': {}"]);
});

test('two seeds that differ only in group ids and mirror chat ids diff clean; a changed checkpoint state does not', () => {
  const first = cleanInput();
  const second = cleanInput();
  second.groups = second.groups.map((group) => ({ ...group, id: `${group.id}9` }));
  second.settings.extension_settings['story-orchestrator'].groupStories = { 179: 'adolion-academy', 189: 'adolion-esha' };
  first.books.push({ name: 'Story Orchestrator - House Nightriver - 2026-09-30@10h00m00s', data: book(1) });
  second.books.push({ name: 'Story Orchestrator - House Nightriver - 2026-09-30@11h11m11s', data: book(1) });
  assert.equal(mirrorName('Story Orchestrator - House Nightriver - x', ['House Nightriver']), 'Story Orchestrator - House Nightriver - <chat>');
  assert.deepEqual(diffInventories(buildInventory(manifest, first), buildInventory(manifest, second)), []);
  const drifted = cleanInput();
  drifted.books[0] = { name: drifted.books[0].name, data: { entries: { 0: { uid: 0, key: ['k0'], content: 'c0', disable: false }, 1: { uid: 1, key: ['k1'], content: 'c1', disable: false } } } };
  const drift = diffInventories(buildInventory(manifest, cleanInput()), buildInventory(manifest, drifted));
  assert.equal(drift.length, 1);
  assert.match(drift[0], /\.enabled: 1 vs 2$/);
});

test('a lane with image or sprite generation on fails, and the strip switches both off before the server starts', () => {
  const input = cleanInput();
  input.settings.extension_settings['story-orchestrator'].settings.image.enabled = true;
  assert.ok(checkInventory(manifest, buildInventory(manifest, input)).some((line) => line.startsWith('media generation is on in the lane (image true, sprites false)')));
  const plan = stripPlan(manifest, { worlds: [], characters: [], chatDirs: [], groups: [], groupChats: [], settings: { extension_settings: { 'story-orchestrator': { settings: { image: { enabled: true, comfyUrl: 'x' } } } } } });
  assert.deepEqual(plan.media, { image: true, sprites: true });
  assert.deepEqual(plan.settings.extension_settings['story-orchestrator'].settings.image, { enabled: false, comfyUrl: 'x' });
  assert.equal(plan.settings.extension_settings['story-orchestrator'].settings.display.briefing, false, 'the lane never opens a briefing over a scripted import');
  assert.equal(plan.settings.extension_settings['story-orchestrator'].settings.sprites.enabled, false);
  assert.equal(plan.settings.extension_settings['story-orchestrator'].settings.sprites.explicit, true);
});

test('plan 15 model config: the lane copy aligns the stale Artemis profile, takes the RP system prompt off non-RP profiles and drops an unrouted dead one', () => {
  const settings: Record<string, any> = { extension_settings: {
    connectionManager: { selectedProfile: 'u', profiles: [
      { id: 'u', name: 'Artemis Local (Unsloth)', preset: 'Artemis v1.1 RP', instruct: 'Gemma 4', sysprompt: 'RP', 'sysprompt-state': 'true' },
      { id: 'old', name: 'Artemis RunPod', preset: 'Artemis v1.1', instruct: 'Gemma 4 Thinking', context: 'Gemma 4', model: 'gemma4-mtp', sysprompt: 'RP', 'sysprompt-state': 'true' },
      { id: 'rp', name: 'Artemis RunPod RP', preset: 'Artemis v1.1 RP', instruct: 'Gemma 4', context: 'Gemma 4', sysprompt: 'RP', 'sysprompt-state': 'true' },
      { id: 'mem', name: 'Story Orchestrator Memory RunPod', preset: 'Artemis Extraction', sysprompt: 'RP', 'sysprompt-state': 'true' },
      { id: 'img', name: 'Image Director', preset: 'Artemis Extraction', sysprompt: 'RP', 'sysprompt-state': 'true' },
      { id: 'dead', name: 'Story Orchestrator Memory Local', 'api-url': 'http://127.0.0.1:1235' },
      { id: 'ds', name: 'deepseek 4.1 flash', api: 'deepseek' },
    ] },
    'story-orchestrator': { settings: { extraction: { profileId: 'ds', profiles: { read: 'ds' } } } },
  } };
  const changes = laneProfiles(settings);
  const byName = Object.fromEntries(settings.extension_settings.connectionManager.profiles.map((profile: any) => [profile.name, profile]));
  assert.deepEqual(Object.keys(byName), ['Artemis Local (Unsloth)', 'Artemis RunPod', 'Artemis RunPod RP', 'Story Orchestrator Memory RunPod', 'Image Director', 'deepseek 4.1 flash']);
  assert.equal(byName['Artemis RunPod'].instruct, 'Gemma 4');
  assert.equal(byName['Artemis RunPod'].preset, 'Artemis v1.1 RP');
  assert.equal(byName['Artemis RunPod'].model, undefined);
  for (const name of ['Story Orchestrator Memory RunPod', 'Image Director']) {
    assert.equal(byName[name].sysprompt, undefined);
    assert.equal(byName[name]['sysprompt-state'], 'false');
  }
  assert.equal(byName['Artemis RunPod RP'].sysprompt, 'RP', 'the RP profile keeps its roleplay system prompt');
  assert.equal(byName['Artemis Local (Unsloth)'].sysprompt, 'RP');
  assert.ok(changes.some((line) => line.startsWith('Story Orchestrator Memory Local: removed')));
  assert.deepEqual(laneProfiles(settings), [], 'a second pass changes nothing');
});

test('control: a dead profile some role still routes to is kept', () => {
  const settings: Record<string, any> = { extension_settings: {
    connectionManager: { profiles: [{ id: 'dead', name: 'Story Orchestrator Memory Local' }] },
    'story-orchestrator': { settings: { extraction: { profileId: 'x', profiles: { curator: 'dead' } } } },
  } };
  assert.deepEqual(laneProfiles(settings), []);
  assert.equal(settings.extension_settings.connectionManager.profiles.length, 1);
});

test('the strip removes the campaign\'s assets from the lane copy and nothing of the user\'s', () => {
  const plan = stripPlan(manifest, {
    worlds: ['Adolion World', 'Adolion Old Draft', 'Story Orchestrator - House Nightriver - c1', 'Story Orchestrator - Sun Ruins - c2', 'Xentar Checkpoints'],
    characters: ['Natalia.png', 'Belle.png', 'Seraphina.png'],
    spriteDirs: ['Natalia', 'Belle Nabba', 'Seraphina'],
    chatDirs: ['Natalia', 'Seraphina'],
    groups: [
      { file: '17.json', id: '17', name: 'Adolion - House Nightriver', chats: ['g1'] },
      { file: '5.json', id: '5', name: 'AdolionGroup', chats: ['g2'] },
    ],
    groupChats: ['g1.jsonl', 'g2.jsonl'],
    settings: {
      active_group: '17', active_character: 'Seraphina.png', tag_map: { 'Belle.png': ['t'], 'Seraphina.png': ['t'] },
      extension_settings: { 'story-orchestrator': { groupStories: { 17: 'adolion-academy', 5: 'mine' }, v2Stories: [{ id: 'adolion-academy' }, { id: 'sun-ruins' }] } },
      world_info_settings: { world_info: { globalSelect: ['Adolion World', 'Xentar Checkpoints'] } },
    },
  });
  assert.deepEqual(plan.worlds, ['Adolion World', 'Adolion Old Draft', 'Story Orchestrator - House Nightriver - c1']);
  assert.deepEqual(plan.characters, ['Natalia.png', 'Belle.png']);
  assert.deepEqual(plan.spriteDirs, ['Natalia', 'Belle Nabba']);
  assert.deepEqual(plan.chatDirs, ['Natalia']);
  assert.deepEqual(plan.groupFiles, ['17.json']);
  assert.deepEqual(plan.groupChats, ['g1.jsonl']);
  const root = plan.settings.extension_settings['story-orchestrator'];
  assert.deepEqual(root.v2Stories, [{ id: 'sun-ruins' }]);
  assert.deepEqual(root.groupStories, { 5: 'mine' });
  assert.deepEqual(plan.settings.world_info_settings.world_info.globalSelect, ['Xentar Checkpoints']);
  assert.equal(plan.settings.active_group, null);
  assert.equal(plan.settings.active_character, 'Seraphina.png');
  assert.deepEqual(Object.keys(plan.settings.tag_map), ['Seraphina.png']);
});

test('v2.6 plan 01 (Saga cast): the open group holds its start cast, and every group left behind holds none', () => {
  assert.deepEqual(manifest.groups.map((group) => expectedStartDisabled(manifest, group)), [[], ['Belle.png']]);
  const input = cleanInput();
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, input)), [], 'without an open-group reading the cast is not judged');
  input.openGroup = 'Adolion - Eshalanore';
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, input)), []);
  input.groups[1].disabled_members = [];
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, input)), ['group Adolion - Eshalanore (open): start cast not in force: disabled missing [Belle.png] extra []']);
  input.openGroup = 'Adolion - House Nightriver';
  input.groups[1].disabled_members = ['Belle.png'];
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, input)), ['group Adolion - Eshalanore: cast left behind after its chat was left: disabled [Belle.png]']);
});

test('T0-3: the strip switches SillyTavern swipes on in the lane copy before the server starts, and records what it found', () => {
  const disk = { worlds: [], characters: [], chatDirs: [], groups: [], groupChats: [], settings: { swipes: false, extension_settings: { 'story-orchestrator': { settings: {} } } } };
  const plan = stripPlan(manifest, disk);
  assert.equal(plan.settings.swipes, true);
  assert.deepEqual(plan.swipes, { was: false, now: true });
  assert.equal(disk.settings.swipes, false, 'the copy is edited, never the settings it was read from');
  assert.deepEqual(stripPlan(manifest, { ...disk, settings: { extension_settings: {} } }).swipes, { was: true, now: true }, 'absent means ST\'s default, which is on');
});

test('T0-3: a lane with swipes off fails the inventory check; the default (absent) passes', () => {
  const off = cleanInput();
  off.settings.swipes = false;
  const inventory = buildInventory(manifest, off);
  assert.equal(inventory.swipes, false);
  assert.ok(checkInventory(manifest, inventory).some((line) => /swipes are off in the lane/.test(line)));
  assert.equal(buildInventory(manifest, cleanInput()).swipes, true);
});

test('T1 fixes: a cast another chat left behind is reset to the campaign initial state, and the open group keeps its start cast', () => {
  const groups = [
    { id: '17', name: 'Adolion - House Nightriver', disabled_members: ['Natalia.png'] },
    { id: '18', name: 'Adolion - Eshalanore', disabled_members: [] },
    { id: '5', name: 'AdolionGroup', disabled_members: ['Belle.png'] },
  ];
  assert.deepEqual(castResetPlan(manifest, groups, 'Adolion - Eshalanore'), [
    { group: 'Adolion - House Nightriver', id: '17', was: ['Natalia.png'], now: [] },
    { group: 'Adolion - Eshalanore', id: '18', was: [], now: ['Belle.png'] },
  ]);
  assert.deepEqual(castResetPlan(manifest, [{ ...groups[0], disabled_members: [] }, { ...groups[1], disabled_members: ['Belle.png'] }], 'Adolion - Eshalanore'), [], 'the intended state needs no reset');
  assert.deepEqual(castResetPlan(manifest, [groups[0], groups[0]], null), [], 'a duplicated group is left to the inventory check');
  const input = cleanInput();
  input.openGroup = 'Adolion - House Nightriver';
  input.groups[1].disabled_members = ['Belle.png'];
  assert.equal(checkInventory(manifest, buildInventory(manifest, input)).length, 1, 'control: without the reset the check fails');
  for (const reset of castResetPlan(manifest, input.groups, input.openGroup)) input.groups.find((group) => group.id === reset.id)!.disabled_members = reset.now;
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, input)), []);
});

test('T1 fixes: drift is measured against the last seed that passed, and a pin move is informational', () => {
  const ok = { file: 'inv-1.json', problems: [], sameAsPrevious: true };
  const failed = { file: 'inv-2.json', problems: ['group Adolion - The Saga: cast left behind'], sameAsPrevious: false };
  const drifted = { file: 'inv-3.json', problems: [], sameAsPrevious: false };
  const reports = [
    { name: 'report-2026-10-01T11-40.json', report: ok },
    { name: 'report-2026-10-01T14-04.json', report: failed },
    { name: 'report-2026-10-01T14-12.json', report: drifted },
    { name: 'check-2026-10-01T15-00.json', report: { file: 'x', problems: [] } },
  ];
  assert.equal(lastGoodSeed(reports)?.name, 'report-2026-10-01T11-40.json');
  assert.equal(lastGoodSeed([{ name: 'report-a.json', report: { problems: [] } }]), null, 'a report without an inventory file is not a baseline');
  assert.equal(lastGoodSeed([]), null);
  const inventory = buildInventory(manifest, cleanInput());
  assert.deepEqual(seedDrift(null, inventory), { sameAsPrevious: null, drift: null });
  assert.deepEqual(seedDrift(inventory, inventory), { sameAsPrevious: true, drift: [] });
  const moved = { ...inventory, commit: 'def456' };
  const pinMove = seedDrift(moved, inventory);
  assert.equal(pinMove.sameAsPrevious, null, 'another campaign build: drift is reported, never failed');
  assert.deepEqual(pinMove.drift, ['$.commit: "def456" vs "abc123"']);
  const sameBuild = seedDrift({ ...inventory, swipes: false }, inventory);
  assert.equal(sameBuild.sameAsPrevious, false, 'same build, real drift still fails');
});

test('T5-1 re-run: a deliberate seeding change is re-accepted as the baseline only by an explicit, recorded acceptance', () => {
  const good = { file: 'inv-1.json', problems: [], sameAsPrevious: true };
  const drifted = { file: 'inv-2.json', problems: [], sameAsPrevious: false, drift: ['$.selected: length 16 vs 0'] };
  const reports = [{ name: 'report-2026-10-02T12-42.json', report: good }, { name: 'report-2026-10-02T14-10.json', report: drifted }];
  assert.equal(lastGoodSeed(reports)?.name, 'report-2026-10-02T12-42.json', 'a drifted seed is never silently a baseline');
  const at = '2026-10-02T15:00:00.000Z';
  assert.deepEqual(acceptBaseline(reports, { reason: ' ', by: 'claude', at }), { refused: 'say why the drift is deliberate: --reason "<why>"' });
  const accepted = acceptBaseline(reports, { reason: 'f7342021: the seed deselects every global book', by: 'claude', at });
  assert.ok('name' in accepted);
  assert.equal(accepted.name, 'report-2026-10-02T14-10.json');
  assert.deepEqual(accepted.report.accepted, { at, by: 'claude', reason: 'f7342021: the seed deselects every global book', drift: ['$.selected: length 16 vs 0'], replaces: 'report-2026-10-02T12-42.json' });
  const after = [reports[0], { name: accepted.name, report: accepted.report }];
  assert.equal(lastGoodSeed(after)?.name, 'report-2026-10-02T14-10.json', 'the accepted seed is the new baseline');
  assert.deepEqual(acceptBaseline(after, { reason: 'again', by: 'claude', at }), { refused: 'report-2026-10-02T14-10.json is already the baseline; nothing to accept' });
  const broken = [...reports, { name: 'report-2026-10-02T14-30.json', report: { file: 'inv-3.json', problems: ['group X: cast left behind'], sameAsPrevious: false } }];
  assert.deepEqual(acceptBaseline(broken, { reason: 'x', by: 'claude', at }), { refused: 'report-2026-10-02T14-30.json has problems (group X: cast left behind); a seed with problems is never a baseline' });
  assert.deepEqual(acceptBaseline(broken, { reason: 'x', by: 'claude', at, report: 'report-2026-10-02T14-10.json' }).hasOwnProperty('name'), true, '--report picks an older drifted seed');
  assert.deepEqual(acceptBaseline([], { reason: 'x', by: 'claude', at }), { refused: 'no seed report on this lane' });
});

test('T6-3-3: the strip disables ST\'s Image Generation extension in the lane copy, keeps the others, and a lane with it on fails', () => {
  assert.equal(IMAGE_EXTENSION, 'stable-diffusion');
  const disk = { worlds: [], characters: [], chatDirs: [], groups: [], groupChats: [], settings: { extension_settings: { disabledExtensions: ['tts', 'third-party/x'], sd: { source: 'comfy' } } } };
  const plan = stripPlan(manifest, disk);
  assert.deepEqual(plan.settings.extension_settings.disabledExtensions, ['tts', 'third-party/x', 'stable-diffusion']);
  assert.deepEqual(plan.imageExtension, { was: true, now: false });
  assert.deepEqual(disk.settings.extension_settings.disabledExtensions, ['tts', 'third-party/x'], 'the disk read is never mutated');
  assert.deepEqual(imageExtensionProblems(plan.settings), []);
  const again = stripPlan(manifest, { ...disk, settings: plan.settings });
  assert.deepEqual(again.settings.extension_settings.disabledExtensions, ['tts', 'third-party/x', 'stable-diffusion']);
  assert.deepEqual(again.imageExtension, { was: false, now: false });
  assert.deepEqual(stripPlan(manifest, { ...disk, settings: {} }).settings.extension_settings.disabledExtensions, ['stable-diffusion']);
  assert.match(imageExtensionProblems(disk.settings)[0], /Image Generation extension \(stable-diffusion\) is enabled in the lane/);
  assert.equal(imageExtensionProblems({}).length, 1, 'a settings file without disabledExtensions is not a pass');
  assert.equal(imageExtensionProblems({ extension_settings: { disabledExtensions: 'stable-diffusion' } }).length, 1);
});
