import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildInventory, buildManifest, checkInventory, diffInventories, installerProblems, mirrorName, parseGroupScript, stripPlan, type InventoryInput } from './adolionFresh.mts';


const GROUP_SCRIPT = `// Generated by scripts/write_group_script.py. Do not edit; rerun the script.
const gc = await import('/scripts/group-chats.js');
const GROUPS = [
 { "name": "Adolion - House Nightriver", "story": "adolion-academy", "members": ["Adolion Narrator.png", "Natalia.png"] },
 { "name": "Adolion - Eshalanore", "story": "adolion-esha", "members": ["Adolion Narrator.png", "Belle.png"] }
];
const out = [];
return out;`;

const book = (count: number) => ({ entries: Object.fromEntries(Array.from({ length: count }, (_, uid) => [String(uid), { uid, key: [`k${uid}`], content: `c${uid}`, disable: uid > 0 }])) });

const FIXED = ['Adolion World', 'Adolion Chronicle', 'Adolion - Aegis City Noble Life', 'Adolion - The Third Kingdom', 'Adolion - Tiunhime Village', 'Adolion - Eshalanore', 'Adolion - Mountains of Shadow'];

const manifest = buildManifest({
  commit: 'abc123',
  stories: [
    { id: 'adolion-academy', version: 21, title: 'House Nightriver', checkpoints: [{}, {}], requirements: { lorebooks: ['Adolion World', 'Adolion Academy Checkpoints'], members: ['Adolion Narrator', 'Natalia'] } },
    { id: 'adolion-esha', version: 6, title: 'Adolion: Eshalanore', checkpoints: [{}], requirements: { lorebooks: ['Adolion World', 'Adolion - Eshalanore'], members: ['Adolion Narrator', 'Belle'] } },
  ],
  cards: ['Adolion Narrator', 'Natalia', 'Belle'].map((name) => ({ avatar: `${name}.png`, data: { data: { name } } })),
  books: [
    ...FIXED.map((name) => ({ name, data: book(2) })),
    { name: 'Adolion Academy Checkpoints', data: book(3) },
    { name: 'Adolion World.report', data: book(1) },
    { name: 'Adolion Adventurer Checkpoints.v1', data: book(1) },
  ],
  groupScript: GROUP_SCRIPT,
});

const cleanInput = (): InventoryInput => ({
  commit: 'abc123',
  books: [...FIXED.map((name) => ({ name, data: book(2) })), { name: 'Adolion Academy Checkpoints', data: book(3) }, { name: 'Xentar Checkpoints', data: book(4) }],
  characters: ['Adolion Narrator.png', 'Natalia.png', 'Belle.png', 'Seraphina.png'],
  groups: [
    { id: '17', name: 'Adolion - House Nightriver', members: ['Natalia.png', 'Adolion Narrator.png'], disabled_members: [] },
    { id: '18', name: 'Adolion - Eshalanore', members: ['Belle.png', 'Adolion Narrator.png'], disabled_members: ['Belle.png'] },
    { id: '5', name: 'AdolionGroup', members: ['Belle.png'] },
  ],
  settings: {
    extension_settings: { 'story-orchestrator': {
      groupStories: { 17: 'adolion-academy', 18: 'adolion-esha' },
      v2Stories: [
        { id: 'adolion-academy', version: 21, hash: 'h1', title: 'House Nightriver', raw: { checkpoints: [{}, {}] } },
        { id: 'adolion-esha', version: 6, hash: 'h2', title: 'Adolion: Eshalanore', raw: { checkpoints: [{}] } },
        { id: 'so-j9-wizard', version: 1, hash: 'h3', title: 'Wizard', raw: {} },
      ],
      settings: { extraction: { enabled: true, cadence: 1, stabilityLag: 0, profileId: 'p' }, image: { enabled: false, comfyUrl: '' }, sprites: { enabled: false } },
    } },
    world_info_settings: { world_info: { globalSelect: ['Adolion World', 'Adolion Academy Checkpoints', 'Adolion - Eshalanore'] } },
  },
  ledger: { lorebooks: manifest.books.map((entry) => entry.name), characters: manifest.cards.map((card) => card.avatar) },
  runtime: {
    'adolion-academy': { ready: true, storyId: 'adolion-academy', missingLorebooks: [], missingMembers: [], missingPersonas: [] },
    'adolion-esha': { ready: true, storyId: 'adolion-esha', missingLorebooks: [], missingMembers: [], missingPersonas: [] },
  },
});

test('the manifest follows the installer: working copies and reports are not books, required books are the union', () => {
  assert.deepEqual(manifest.books.map((entry) => entry.name).sort(), [...FIXED, 'Adolion Academy Checkpoints'].sort());
  assert.deepEqual(manifest.requiredBooks, ['Adolion - Eshalanore', 'Adolion Academy Checkpoints', 'Adolion World']);
  assert.deepEqual(manifest.groups.map((group) => group.story), ['adolion-academy', 'adolion-esha']);
  assert.throws(() => parseGroupScript('const x = 1;'), /no `const GROUPS/);
});

test('a clean seed passes the check, and a stranger\'s book, card or story is not counted as ours', () => {
  assert.deepEqual(checkInventory(manifest, buildInventory(manifest, cleanInput())), []);
});

test('a planted missing book fails the check and names every story it leaves unready', () => {
  const input = cleanInput();
  input.books = input.books.filter((entry) => entry.name !== 'Adolion - Eshalanore');
  const worldInfo = input.settings.world_info_settings.world_info;
  worldInfo.globalSelect = worldInfo.globalSelect.filter((name: string) => name !== 'Adolion - Eshalanore');
  input.runtime!['adolion-esha'] = { ready: false, storyId: 'adolion-esha', missingLorebooks: ['Adolion - Eshalanore'], missingMembers: [], missingPersonas: [] };
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.includes('book missing: Adolion - Eshalanore'), problems.join('\n'));
  assert.ok(problems.some((line) => line.startsWith('required books not selected: Adolion - Eshalanore')));
  assert.ok(problems.some((line) => line.startsWith('story adolion-esha not ready (install): lorebooks [Adolion - Eshalanore]')));
  assert.ok(problems.some((line) => line.startsWith('story adolion-esha not ready (runtime')));
  assert.ok(!problems.some((line) => line.startsWith('story adolion-academy')));
});

test('a book that is listed but not selected still leaves its story unready', () => {
  const input = cleanInput();
  input.settings.world_info_settings.world_info.globalSelect = ['Adolion World', 'Adolion Academy Checkpoints', 'Xentar Checkpoints'];
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.some((line) => line.startsWith('story adolion-esha not ready (install)')));
  assert.ok(problems.includes('selected books no Adolion story requires: Xentar Checkpoints'));
});

test('an installer SKIP, a lost group binding, a stale library version and a missing member each fail', () => {
  const input = cleanInput();
  input.ledger = { lorebooks: input.ledger!.lorebooks!, characters: ['Natalia.png'] };
  input.settings.extension_settings['story-orchestrator'].groupStories = { 17: 'adolion-academy' };
  input.settings.extension_settings['story-orchestrator'].v2Stories[0].version = 20;
  input.characters = input.characters.filter((avatar) => avatar !== 'Natalia.png');
  const problems = checkInventory(manifest, buildInventory(manifest, input));
  assert.ok(problems.some((line) => line.startsWith('installer ledger cards differ')));
  assert.ok(problems.includes('group Adolion - Eshalanore: bound to nothing, want adolion-esha'));
  assert.ok(problems.some((line) => line.startsWith('story adolion-academy: library v20')));
  assert.ok(problems.includes('cards missing: Natalia.png'));
  assert.ok(problems.some((line) => line.startsWith('story adolion-academy not ready (install): lorebooks [] members [Natalia]')));
  assert.deepEqual(installerProblems('lorebook Adolion World (264 entries)\nSKIP card \'Belle\': already installed\nFAIL card \'X\': {}'), ["SKIP card 'Belle': already installed", "FAIL card 'X': {}"]);
});

test('two seeds that differ only in group ids and mirror chat ids diff clean; a changed checkpoint state does not', () => {
  const first = cleanInput();
  const second = cleanInput();
  second.groups = second.groups.map((group) => ({ ...group, id: `${group.id}9` }));
  second.settings.extension_settings['story-orchestrator'].groupStories = { 179: 'adolion-academy', 189: 'adolion-esha' };
  first.books.push({ name: 'Story Orchestrator - House Nightriver - 2026-09-30@10h00m00s', data: book(1) });
  second.books.push({ name: 'Story Orchestrator - House Nightriver - 2026-09-30@11h11m11s', data: book(1) });
  assert.equal(mirrorName('Story Orchestrator - House Nightriver - x', ['House Nightriver']), 'Story Orchestrator - House Nightriver - <chat>');
  assert.deepEqual(diffInventories(buildInventory(manifest, first), buildInventory(manifest, second)), []);
  const drifted = cleanInput();
  drifted.books[0] = { name: drifted.books[0].name, data: { entries: { 0: { uid: 0, key: ['k0'], content: 'c0', disable: false }, 1: { uid: 1, key: ['k1'], content: 'c1', disable: false } } } };
  const drift = diffInventories(buildInventory(manifest, cleanInput()), buildInventory(manifest, drifted));
  assert.equal(drift.length, 1);
  assert.match(drift[0], /\.enabled: 1 vs 2$/);
});

test('a lane with image or sprite generation on fails, and the strip switches both off before the server starts', () => {
  const input = cleanInput();
  input.settings.extension_settings['story-orchestrator'].settings.image.enabled = true;
  assert.ok(checkInventory(manifest, buildInventory(manifest, input)).some((line) => line.startsWith('media generation is on in the lane (image true, sprites false)')));
  const plan = stripPlan(manifest, { worlds: [], characters: [], chatDirs: [], groups: [], groupChats: [], settings: { extension_settings: { 'story-orchestrator': { settings: { image: { enabled: true, comfyUrl: 'x' } } } } } });
  assert.deepEqual(plan.media, { image: true, sprites: true });
  assert.deepEqual(plan.settings.extension_settings['story-orchestrator'].settings.image, { enabled: false, comfyUrl: 'x' });
  assert.equal(plan.settings.extension_settings['story-orchestrator'].settings.sprites.enabled, false);
});

test('the strip removes the campaign\'s assets from the lane copy and nothing of the user\'s', () => {
  const plan = stripPlan(manifest, {
    worlds: ['Adolion World', 'Adolion Old Draft', 'Story Orchestrator - House Nightriver - c1', 'Story Orchestrator - Sun Ruins - c2', 'Xentar Checkpoints'],
    characters: ['Natalia.png', 'Belle.png', 'Seraphina.png'],
    chatDirs: ['Natalia', 'Seraphina'],
    groups: [
      { file: '17.json', id: '17', name: 'Adolion - House Nightriver', chats: ['g1'] },
      { file: '5.json', id: '5', name: 'AdolionGroup', chats: ['g2'] },
    ],
    groupChats: ['g1.jsonl', 'g2.jsonl'],
    settings: {
      active_group: '17', active_character: 'Seraphina.png', tag_map: { 'Belle.png': ['t'], 'Seraphina.png': ['t'] },
      extension_settings: { 'story-orchestrator': { groupStories: { 17: 'adolion-academy', 5: 'mine' }, v2Stories: [{ id: 'adolion-academy' }, { id: 'sun-ruins' }] } },
      world_info_settings: { world_info: { globalSelect: ['Adolion World', 'Xentar Checkpoints'] } },
    },
  });
  assert.deepEqual(plan.worlds, ['Adolion World', 'Adolion Old Draft', 'Story Orchestrator - House Nightriver - c1']);
  assert.deepEqual(plan.characters, ['Natalia.png', 'Belle.png']);
  assert.deepEqual(plan.chatDirs, ['Natalia']);
  assert.deepEqual(plan.groupFiles, ['17.json']);
  assert.deepEqual(plan.groupChats, ['g1.jsonl']);
  const root = plan.settings.extension_settings['story-orchestrator'];
  assert.deepEqual(root.v2Stories, [{ id: 'sun-ruins' }]);
  assert.deepEqual(root.groupStories, { 5: 'mine' });
  assert.deepEqual(plan.settings.world_info_settings.world_info.globalSelect, ['Xentar Checkpoints']);
  assert.equal(plan.settings.active_group, null);
  assert.equal(plan.settings.active_character, 'Seraphina.png');
  assert.deepEqual(Object.keys(plan.settings.tag_map), ['Seraphina.png']);
});
