const V = globalThis.__soV25; const S = globalThis.__soT13; const rt = globalThis.storyOrchestratorRuntime;
const wi = rt.getGlobalSettings().worldInfo;
if (wi.gatingMode !== 'file' || Object.keys(wi.normalized ?? {}).length) throw new Error('lane not fresh');
const gated = V.gated(); const books = [...gated.keys()];
const saved = await V.saveBooks(books);
V.save({ books, probe: true, startedAt: new Date().toISOString() });
S.arm(); S.reset();
const activation = await V.confirmScan();
await new Promise((r) => setTimeout(r, 1500));
const ledger = rt.getGlobalSettings().worldInfo.normalized;
const book = books.find((n) => (ledger[n] ?? []).length);
return { saved, books, activation, ledgerCount: Object.values(ledger).reduce((n, a) => n + a.length, 0), mode: rt.getGlobalSettings().worldInfo.gatingMode, g5: { book, comment: ledger[book][0] }, status: rt.getSnapshot().wiGating && { active: rt.getSnapshot().wiGating.active, drift: rt.getSnapshot().wiGating.drift?.length, missingKey: rt.getSnapshot().wiGating.missingKey?.length } };
